version: "2"

services:
  loraserver:
    image: loraserver/loraserver:2.0.0
    volumes:
      - ./configuration/loraserver:/etc/loraserver

  appserver:
    image: loraserver/lora-app-server:2
    volumes:
      - ./configuration/lora-app-server:/etc/lora-app-server

  gatewaybridge:
    image: loraserver/lora-gateway-bridge:2
    volumes:
      - ./configuration/lora-gateway-bridge:/etc/lora-gateway-bridge

  postgresql:
    image: postgres:9.6-alpine
    volumes:
      - ./configuration/postgresql/initdb:/docker-entrypoint-initdb.d
      - ./data/postgresql:/var/lib/postgresql/data

  redis:
    image: redis:4-alpine
    volumes:
      - ./data/redis:/data

  mosquitto:
    image: eclipse-mosquitto

  nginx:
    build: ./configuration/nginx/
    ports:
      - 80:2376/udp
      - 80:2376
